return {}
-- return {
--   "jose-elias-alvarez/null-ls.nvim",
--   opts = function(_, config)
--     -- config variable is the default configuration table for the setup function call
--     local null_ls = require "null-ls"
--     local formatting = null_ls.builtins.formatting
--     local diagnostics = null_ls.builtins.diagnostics
--
--     -- Check supported formatters and linters
--     -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
--     -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
--     -- null_ls.builtins.diagnostics.eslint.with({
--     --   extra_args = { "-c", vim.fn.expand("~/.config/.eslintrc.json") },
--     --   prefer_local = "node_modules/.bin",
--     -- })
--
--     config.sources = {
--       diagnostics.eslint,
--       -- diagnostics.rubocop,
--       formatting.prettier,
--       -- formatting.eslint_d.with({
--       --   condition = function(utils)
--       --     return utils.has_file({ ".eslintrc" })
--       --   end,
--       -- }),
--       -- formatting.eslint,
--       -- formatting.rubocop,
--       -- formatting.fixjson,
--
--     }
--     return config -- return final config table
--   end,
-- }
