# Zsh Path to your oh-my-zsh configuration.
ZSH="$HOME/.dotfiles/oh-my-zsh"
ZSH_THEME="af-magic"
plugins=(ant z git brew bundler gem history-substring-search osx rails ruby nvm command-not-found)

# For pkg-config to find zlib you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

# Autocomplete
COMPLETION_WAITING_DOTS="true"

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Options
unsetopt correct_all
unsetopt correct

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/dev_scripts/k.sh
source $HOME/.dotfiles/shell/aliases
source $HOME/.dotfiles/shell/functions

export EDITOR="lvim"
export BUNDLER_EDITOR="lvim"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"^
export CC=/usr/bin/gcc
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/X11/bin:/usr/local/share/npm/bin:$PATH:`yarn global bin`"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# NVM config
export NVM_DIR="$HOME/.nvm"
NVM_HOMEBREW="/usr/local/opt/nvm/nvm.sh"
[ -s "$NVM_HOMEBREW" ] && \. "$NVM_HOMEBREW"

eval "$(ssh-agent -s)"
eval "$(rbenv init -)"

autoload -U add-zsh-hook
use_nvmrc_version_automatically() {
  if [[ -f .nvmrc ]]; then
    echo ".nvmrc FOUND now INSTALLING and USING $(cat .nvmrc)"
    nvm install $(cat .nvmrc) && nvm use $(cat .nvmrc)
  fi
}
add-zsh-hook chpwd use_nvmrc_version_automatically
use_nvmrc_version_automatically

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
