- defaults:
      link:
          create: true
          relink: true
          force: true

- clean: ["~"]

- shell:
      - [git submodule update --init --recursive, Installing submodules]

- link:
      ~/.dev_scripts: dev_scripts
      ~/.oh-my-zsh: oh-my-zsh
      ~/.gemrc: gemrc
      ~/.gitconfig: gitconfig
      ~/.gitignore: gitignore
      ~/.irbrc: irbrc
      ~/.screenrc: screenrc
      ~/.psqlrc: psqlrc
      ~/.zlogin: zlogin
      ~/.zlogout: zlogout
      ~/.zshenv: zshenv
