- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- link:
    ~/.dev_scripts: dev_scripts
    ~/.oh-my-zsh: oh-my-zsh
    ~/.gemrc: gemrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.irbrc: irbrc
    ~/.screenrc: screenrc
    ~/.psqlrc: psqlrc
    ~/.zlogin: zlogin
    ~/.zlogout: zlogout
    ~/.zshenv: zshenv
    ~/.janus: vim-config/janus
    ~/.vimrc.before: vim-config/vimrc.before
    ~/.vimrc.after: vim-config/vimrc.after
- shell:
    - [git submodule update --init --recursive, Installing submodules]