- link:
    ~/.zshrc: linux/zshrc
    ~/.dotfiles/dev_scripts/services.rb: linux/services.rb
    ~/.themes: themes

# - brew:
#     - ack
#     - autoconf
#     - ffmpeg
#     - fontconfig
#     - gcc
#     - geoip
#     - gh
#     - gifsicle
#     - gist
#     - git
#     - graphicsmagick
#     - imagemagick
#     - memcached
#     - node
#     - openssl
#     - ossp-uuid
#     - phantomjs
#     - pngcrush
#     - postgres
#     - python
#     - rbenv
#     - readline
#     - redis
#     - ruby-build
#     - ruby-install
#     - spark
#     - sqlite
#     - tig
#     - watchman
#     - webkit2png
#     - z
#     - zsh

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - ["chsh -s /bin/zsh", Set zsh as the default shell]
    - gem install bundler
