- link:
  ~/.zshrc: mac/zshrc
  ~/.atom/config.cson: mac/atom.cson
  ~/.osx: mac/osx

- brew:
  - ack
  - advancecomp
  - atk
  - augeas
  - autoconf
  - c-ares
  - cairo
  - certbot
  - chromaprint
  - chromedriver
  - cmatrix
  - colordiff
  - d-bus -> dbus
  - dbus
  - dialog
  - eigen
  - ffmpeg
  - fontconfig
  - fortune
  - freetype
  - gcc
  - gdbm
  - gdk-pixbuf
  - geoip
  - gettext
  - gh
  - gifsicle
  - gist
  - git
  - git-flow-avh
  - glib
  - gmp
  - gnu-getopt
  - gnutls
  - go
  - gobject-introspection
  - graphicsmagick
  - gsettings-desktop-schemas
  - gtk+3
  - harfbuzz
  - hicolor-icon-theme
  - htop
  - icu4c
  - ilmbase
  - imagemagick
  - isl
  - jhead
  - jpeg
  - jpegoptim
  - jq
  - klavaro
  - lame
  - libepoxy
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libmpc
  - libmxml
  - libpng
  - libtasn1
  - libtiff
  - libtool
  - libusb
  - libvo-aacenc
  - libxml2
  - libyaml
  - little-cms2
  - lynx
  - media-info
  - memcached
  - mongodb
  - mp3val
  - mpfr
  - mysql
  - nettle
  - nginx
  - node
  - numpy
  - oniguruma
  - opencv
  - openexr
  - openjpeg
  - openssl
  - optipng
  - ossp-uuid
  - pango
  - pcre
  - phantomjs
  - pixman
  - pkg-config
  - pngcrush
  - pngquant
  - python
  - qt
  - qt5
  - rbenv
  - readline
  - redis
  - ruby-build
  - ruby-install
  - spark
  - sphinx
  - sqlite
  - terminal-notifier
  - tig
  - tmux
  - tree
  - utf8proc
  - watchman
  - webkit2png
  - wget
  - wifi-password
  - wireshark
  - x264
  - xvid
  - xz
  - z
  - zsh

- shell:
  - [chsh -s /bin/zsh, Set zsh as the default shell]
  - [git submodule update --init --recursive, Installing submodules]
  - [apm install --packages-file ~/.dotfiles/atom/package-list.txt, Installing atom packages]
  - "./install -p dotbot-apt-get/aptget.py -c packages.conf.yaml"
  - brew cleanup --force
  - brew cask cleanup
  - rm -f -r /Library/Caches/Homebrew/*
