- clean: ~/.atom/config.cson

- link:
    ~/.zshrc: mac/zshrc
    ~/.atom/config.cson: mac/atom.cson
    ~/.osx: mac/osx
    ~/.dotfiles/dev_scripts/services.rb: mac/services.rb

- brew:
    - ack
    - autoconf
    - cmatrix
    - gcc
    - geoip
    - gh
    - gifsicle
    - gist
    - git
    - graphicsmagick
    - imagemagick
    - memcached
    - mongodb
    - mysql
    - nginx
    - node
    - openssl
    - ossp-uuid
    - phantomjs
    - pngcrush
    - postgresql
    - python
    - rbenv
    - readline
    - redis
    - ruby-build
    - ruby-install
    - spark
    - sqlite
    - terminal-notifier
    - tig
    - watchman
    - webkit2png
    - wifi-password
    - z
    - zsh

- shell:
    - [git submodule update --recursive, Installing submodules]
    - [brew cleanup --force, Brew cleanup]
    - brew cask cleanup
    - rm -f -r /Library/Caches/Homebrew/*
    - [apm install --packages-file ~/.dotfiles/atom/package-list.txt, Installing atom packages]
    - [chsh -s /bin/zsh, Set zsh as the default shell]
    - [gem install bundler, Installing bundler]
    - [initdb -D /usr/local/var/postgres, Setting up postgres]
    - ['gem install pg -- --with-pg-config=/usr/local/bin/pg_config', Installing postgres gem]
