# Zsh-
# Path to your oh-my-zsh configuration.
ZSH="$HOME/.dotfiles/oh-my-zsh"

# Autocomplete
COMPLETION_WAITING_DOTS="true"

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

export EDITOR="atom"
export BUNDLER_EDITOR="atom"

ZSH_THEME="hyperzsh"

export DROPBOX="$HOME/Documents/Dropbox"

plugins=(atom ant z zsh-syntax-highlighting git brew bundler gem git-flow history-substring-search rails ruby ssh-agent cap zeus boris k)

# Options
unsetopt correct_all
unsetopt correct

# Oh My Zsh
source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/dev_scripts/k.sh

# Aliases/functions
source $HOME/.dotfiles/shell/aliases
source $HOME/.dotfiles/shell/functions

export PATH="$HOME/.rbenv/bin:$PATH:/usr/bin:/usr/local/bin:/bin"
export PATH="$HOME/.yarn/bin:$PATH"
eval "$(rbenv init -)"